env:
  commonjs: true
  es2021: true
  node: true
extends: eslint:recommended
parserOptions:
  ecmaVersion: latest
rules:
  arrow-body-style: 'error'
  no-var: 'error'
  prefer-const: 'error'
  object-shorthand: 'error'
