name: datapack

on: [push]

env:
  FABRIC_API: https://cdn.modrinth.com/data/P7dR8mSH/versions/JMCwDuki/fabric-api-0.92.0%2B1.20.4.jar
  FABRIC_SERVER: https://meta.fabricmc.net/v2/versions/loader/1.20.4/0.15.3/0.11.2/server/jar
  PACKTEST: https://cdn.modrinth.com/data/XsKUhp45/versions/Gq3rUEy6/packtest-1.3-mc1.20.4.jar

# TODO(37): add linting
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Download server files
        run: |
          curl -o server.jar $FABRIC_SERVER
          mkdir mods
          curl -o mods/fabric-api.jar $FABRIC_API
          curl -o mods/packtest.jar $PACKTEST

      - name: Copy packs to world
        run: |
          mkdir -p world/datapacks
          cp -r datapacks world/datapacks

      - name: Run test server
        run: |
          java -Xmx2G -Dpacktest.auto -jar server.jar nogui
