name: datapack

on: [push]

env:
  FABRIC_API: https://cdn.modrinth.com/data/P7dR8mSH/versions/JMCwDuki/fabric-api-0.92.0%2B1.20.4.jar
  FABRIC_SERVER: https://meta.fabricmc.net/v2/versions/loader/1.20.4/0.15.3/0.11.2/server/jar
  PACKTEST: https://cdn.modrinth.com/data/XsKUhp45/versions/Gq3rUEy6/packtest-1.3-mc1.20.4.jar

  BLOCKBENCH_PATH: null
  MINECRAFT_PATH: null
  RESOURCEPACK_NAME: omega-flowey-remastered-resourcepack
  WORLD_NAME: omega-flowey-remastered

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Yarn 3.6.3
        run: corepack enable
      - name: Setup cache
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          node-version-file: package.json
      - run: yarn
      - name: Run lint scripts on datapacks
        run: yarn start lint.custom.datapacks
        env:
          FORCE_COLOR: 2

  test:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Download server files
        run: |
          curl -o server.jar $FABRIC_SERVER
          mkdir mods
          curl -o mods/fabric-api.jar $FABRIC_API
          curl -o mods/packtest.jar $PACKTEST
      - name: Copy packs to world
        run: |
          mkdir -p world
          cp -r datapacks world
      - name: Run test server
        run: |
          java -Xmx2G -Dpacktest.auto -jar server.jar nogui
