name: resourcepack

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yarn
      - name: Run lint scripts on resourcepack
        run: yarn start lint.custom.resourcepack
        env:
          FORCE_COLOR: 2
