name: scripts

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: tw3lveparsecs/github-actions-set-variables@v0.2
        with:
          envFilePath: ./.github/variables/shared.env
      - name: Install Yarn 3.6.3
        run: corepack enable
      - name: Setup cache
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          node-version-file: package.json
      - run: yarn
      - name: Run Prettier
        run: yarn start lint.scripts.prettier.check

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v4
      - uses: tw3lveparsecs/github-actions-set-variables@v0.2
        with:
          envFilePath: ./.github/variables/shared.env
      - name: Install Yarn 3.6.3
        run: corepack enable
      - name: Setup cache
        uses: actions/setup-node@v4
        with:
          cache: 'yarn'
          cache-dependency-path: yarn.lock
          node-version-file: package.json
      - run: yarn
      - name: Run ESLint
        run: yarn start lint.scripts.eslint.check
      - name: Run custom lint scripts on non-datapacks, non-resourcepack files
        run: yarn start lint.custom.other
        env:
          FORCE_COLOR: 2
