name: scripts

on: [push]

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yarn
      - name: Run Prettier
        run: yarn start lint.scripts.prettier.check

  lint:
    runs-on: ubuntu-latest
    needs: format
    steps:
      - uses: actions/checkout@v4
      - uses: ./.github/actions/setup-yarn
      - name: Run ESLint
        run: yarn start lint.scripts.eslint.check
      - name: Run custom lint scripts on non-datapacks, non-resourcepack files
        run: yarn start lint.custom.other
        env:
          FORCE_COLOR: 2
